const DATE_TIME_FORMATS = {
  DATE: "MM/DD/YYYY",
  TIME: "hh:mm A",
  DATETIME: "MM/DD/YYYY hh:mm A",

  DATE_SHORT: "MM/DD",
  DATE_TIME_SHORT: "MM/DD hh:mm A",

  ISO: "YYYY-MM-DD",
  ISO_DATETIME: "YYYY-MM-DDTHH:mm:ssZ",
}

export { DATE_TIME_FORMATS }
